// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNGGXHuHds5hPSOsHnd0rpYJmpiAFbvtc',
    appId: '1:87320023160:web:4d6f5b52694048bb969d8d',
    messagingSenderId: '87320023160',
    projectId: 'weight-measure-188ec',
    authDomain: 'weight-measure-188ec.firebaseapp.com',
    storageBucket: 'weight-measure-188ec.firebasestorage.app',
    measurementId: 'G-YWKFHK6MXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmA7i4B3mtw8TpPs2Wlv977GcZB2cUxKQ',
    appId: '1:87320023160:android:193eebbbdacd6e1e969d8d',
    messagingSenderId: '87320023160',
    projectId: 'weight-measure-188ec',
    storageBucket: 'weight-measure-188ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk65cBAmNVVE1r1L0tybl7ERQWSeY3YRI',
    appId: '1:87320023160:ios:8f4cc15a608859ec969d8d',
    messagingSenderId: '87320023160',
    projectId: 'weight-measure-188ec',
    storageBucket: 'weight-measure-188ec.firebasestorage.app',
    iosBundleId: 'com.example.weightMeasure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNGGXHuHds5hPSOsHnd0rpYJmpiAFbvtc',
    appId: '1:87320023160:web:a96c0c71a1469395969d8d',
    messagingSenderId: '87320023160',
    projectId: 'weight-measure-188ec',
    authDomain: 'weight-measure-188ec.firebaseapp.com',
    storageBucket: 'weight-measure-188ec.firebasestorage.app',
    measurementId: 'G-MLWHR7X4H8',
  );
}
